name: CI project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build